### ISSUE TITLE
例子没有正常显示

### ISSUE THREAD

**Issue by yelloxing** [handless-ui/uniQuery#2]
![IMG_0079](https://github.com/oi-contrib/uniQuery/assets/23074691/989508ba-de7f-46cf-82b3-d1d3155afcf3)

**Comment by zxl20070701** [comment]
初步排查好像是下面这个文件无法正常加载导致：

```js
https://oi-contrib.github.io/uniQuery/examples/assets/_plugin-vue_export-helper.1b428a4d.js
```

好像下划线_开头的就是无法正确请求，都是404，具体原因和解决方案需要有空排查一下

**Comment by zxl20070701** [comment]
已经修复
